# fly.toml app configuration file generated for ed-summariser-server on 2025-04-30T00:30:53+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ed-summariser-server'
primary_region = 'syd'

[processes]
  app = "/app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000"
  worker = "/app/.venv/bin/python celery_worker.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app'] 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ["worker"]  # This VM runs the worker
